# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_list', '0003_auto_20170926_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='user',
        ),
    ]
